package jp.co.ikitsuke.dataAccess.entity;

import java.util.Date;

public class Login {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.user_id
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.mail_address
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.login_password
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	private String loginPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.create_date_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	private Date createDateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.update_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.user_id
	 * @return  the value of login.user_id
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.user_id
	 * @param userId  the value for login.user_id
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.mail_address
	 * @return  the value of login.mail_address
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.mail_address
	 * @param mailAddress  the value for login.mail_address
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.login_password
	 * @return  the value of login.login_password
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.login_password
	 * @param loginPassword  the value for login.login_password
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.create_date_time
	 * @return  the value of login.create_date_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public Date getCreateDateTime() {
		return createDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.create_date_time
	 * @param createDateTime  the value for login.create_date_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.update_time
	 * @return  the value of login.update_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.update_time
	 * @param updateTime  the value for login.update_time
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}