package jp.co.ikitsuke.dataAccess.entity;

import java.util.Date;

public class ShopInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_tel
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String shopTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_memo
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String shopMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_page_url
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String shopPageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.delete_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_id
     *
     * @return the value of shop_info.shop_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_id
     *
     * @param shopId the value for shop_info.shop_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.category_id
     *
     * @return the value of shop_info.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.category_id
     *
     * @param categoryId the value for shop_info.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_name
     *
     * @return the value of shop_info.shop_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_name
     *
     * @param shopName the value for shop_info.shop_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_tel
     *
     * @return the value of shop_info.shop_tel
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getShopTel() {
        return shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_tel
     *
     * @param shopTel the value for shop_info.shop_tel
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setShopTel(String shopTel) {
        this.shopTel = shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_memo
     *
     * @return the value of shop_info.shop_memo
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getShopMemo() {
        return shopMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_memo
     *
     * @param shopMemo the value for shop_info.shop_memo
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setShopMemo(String shopMemo) {
        this.shopMemo = shopMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_page_url
     *
     * @return the value of shop_info.shop_page_url
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getShopPageUrl() {
        return shopPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_page_url
     *
     * @param shopPageUrl the value for shop_info.shop_page_url
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setShopPageUrl(String shopPageUrl) {
        this.shopPageUrl = shopPageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.delete_flag
     *
     * @return the value of shop_info.delete_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.delete_flag
     *
     * @param deleteFlag the value for shop_info.delete_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.last_update_time
     *
     * @return the value of shop_info.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.last_update_time
     *
     * @param lastUpdateTime the value for shop_info.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}