package jp.co.ikitsuke.dataAccess.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ShopInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public ShopInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(Integer value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(Integer value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(Integer value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(Integer value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(Integer value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<Integer> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<Integer> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(Integer value1, Integer value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdEqualTo(Integer value) {
			addCriterion("category_id =", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotEqualTo(Integer value) {
			addCriterion("category_id <>", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThan(Integer value) {
			addCriterion("category_id >", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("category_id >=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThan(Integer value) {
			addCriterion("category_id <", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("category_id <=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIn(List<Integer> values) {
			addCriterion("category_id in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotIn(List<Integer> values) {
			addCriterion("category_id not in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("category_id not between", value1, value2,
					"categoryId");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopTelIsNull() {
			addCriterion("shop_tel is null");
			return (Criteria) this;
		}

		public Criteria andShopTelIsNotNull() {
			addCriterion("shop_tel is not null");
			return (Criteria) this;
		}

		public Criteria andShopTelEqualTo(String value) {
			addCriterion("shop_tel =", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelNotEqualTo(String value) {
			addCriterion("shop_tel <>", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelGreaterThan(String value) {
			addCriterion("shop_tel >", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelGreaterThanOrEqualTo(String value) {
			addCriterion("shop_tel >=", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelLessThan(String value) {
			addCriterion("shop_tel <", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelLessThanOrEqualTo(String value) {
			addCriterion("shop_tel <=", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelLike(String value) {
			addCriterion("shop_tel like", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelNotLike(String value) {
			addCriterion("shop_tel not like", value, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelIn(List<String> values) {
			addCriterion("shop_tel in", values, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelNotIn(List<String> values) {
			addCriterion("shop_tel not in", values, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelBetween(String value1, String value2) {
			addCriterion("shop_tel between", value1, value2, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopTelNotBetween(String value1, String value2) {
			addCriterion("shop_tel not between", value1, value2, "shopTel");
			return (Criteria) this;
		}

		public Criteria andShopMemoIsNull() {
			addCriterion("shop_memo is null");
			return (Criteria) this;
		}

		public Criteria andShopMemoIsNotNull() {
			addCriterion("shop_memo is not null");
			return (Criteria) this;
		}

		public Criteria andShopMemoEqualTo(String value) {
			addCriterion("shop_memo =", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoNotEqualTo(String value) {
			addCriterion("shop_memo <>", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoGreaterThan(String value) {
			addCriterion("shop_memo >", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoGreaterThanOrEqualTo(String value) {
			addCriterion("shop_memo >=", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoLessThan(String value) {
			addCriterion("shop_memo <", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoLessThanOrEqualTo(String value) {
			addCriterion("shop_memo <=", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoLike(String value) {
			addCriterion("shop_memo like", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoNotLike(String value) {
			addCriterion("shop_memo not like", value, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoIn(List<String> values) {
			addCriterion("shop_memo in", values, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoNotIn(List<String> values) {
			addCriterion("shop_memo not in", values, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoBetween(String value1, String value2) {
			addCriterion("shop_memo between", value1, value2, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopMemoNotBetween(String value1, String value2) {
			addCriterion("shop_memo not between", value1, value2, "shopMemo");
			return (Criteria) this;
		}

		public Criteria andShopUrlIsNull() {
			addCriterion("shop_url is null");
			return (Criteria) this;
		}

		public Criteria andShopUrlIsNotNull() {
			addCriterion("shop_url is not null");
			return (Criteria) this;
		}

		public Criteria andShopUrlEqualTo(String value) {
			addCriterion("shop_url =", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlNotEqualTo(String value) {
			addCriterion("shop_url <>", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlGreaterThan(String value) {
			addCriterion("shop_url >", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlGreaterThanOrEqualTo(String value) {
			addCriterion("shop_url >=", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlLessThan(String value) {
			addCriterion("shop_url <", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlLessThanOrEqualTo(String value) {
			addCriterion("shop_url <=", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlLike(String value) {
			addCriterion("shop_url like", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlNotLike(String value) {
			addCriterion("shop_url not like", value, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlIn(List<String> values) {
			addCriterion("shop_url in", values, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlNotIn(List<String> values) {
			addCriterion("shop_url not in", values, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlBetween(String value1, String value2) {
			addCriterion("shop_url between", value1, value2, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andShopUrlNotBetween(String value1, String value2) {
			addCriterion("shop_url not between", value1, value2, "shopUrl");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNull() {
			addCriterion("delete_flag is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIsNotNull() {
			addCriterion("delete_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagEqualTo(String value) {
			addCriterion("delete_flag =", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotEqualTo(String value) {
			addCriterion("delete_flag <>", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThan(String value) {
			addCriterion("delete_flag >", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
			addCriterion("delete_flag >=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThan(String value) {
			addCriterion("delete_flag <", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
			addCriterion("delete_flag <=", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagLike(String value) {
			addCriterion("delete_flag like", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotLike(String value) {
			addCriterion("delete_flag not like", value, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagIn(List<String> values) {
			addCriterion("delete_flag in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotIn(List<String> values) {
			addCriterion("delete_flag not in", values, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagBetween(String value1, String value2) {
			addCriterion("delete_flag between", value1, value2, "deleteFlag");
			return (Criteria) this;
		}

		public Criteria andDeleteFlagNotBetween(String value1, String value2) {
			addCriterion("delete_flag not between", value1, value2,
					"deleteFlag");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCDate("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table shop_info
	 * @mbggenerated  Sun Dec 07 22:06:14 JST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_info
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 04 20:22:10 JST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}