package jp.co.ikitsuke.dataAccess.entity;

import java.util.Date;

public class ShopCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_category.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_category.category_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_category.user_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_category.disable_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private String disableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_category.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_category.category_id
     *
     * @return the value of shop_category.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_category.category_id
     *
     * @param categoryId the value for shop_category.category_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_category.category_name
     *
     * @return the value of shop_category.category_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_category.category_name
     *
     * @param categoryName the value for shop_category.category_name
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_category.user_id
     *
     * @return the value of shop_category.user_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_category.user_id
     *
     * @param userId the value for shop_category.user_id
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_category.disable_flag
     *
     * @return the value of shop_category.disable_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public String getDisableFlag() {
        return disableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_category.disable_flag
     *
     * @param disableFlag the value for shop_category.disable_flag
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setDisableFlag(String disableFlag) {
        this.disableFlag = disableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_category.last_update_time
     *
     * @return the value of shop_category.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_category.last_update_time
     *
     * @param lastUpdateTime the value for shop_category.last_update_time
     *
     * @mbggenerated Thu Dec 04 20:22:10 JST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}